name: Build TWRPs

on:
  push:
    paths:
      - ".github/workflows/twrp.yml"
  workflow_dispatch:
  schedule:
    - cron: "14 13 * * 5"

jobs:
  Build-TWRP:
    name: "🐎 Build TWRP"
    runs-on: ubuntu-latest
    steps:
      # Set swap space
      - name: 📐 Prepare the build environment 
        run: |
          cd ~
          sudo apt install git aria2 -y
          git clone https://gitlab.com/OrangeFox/misc/scripts
          cd scripts
          sudo bash setup/android_build_env.sh
          sudo bash setup/install_android_sdk.sh

      - name: 😄 Sync OrangeFox sources and minimal manifest
        run: |
          mkdir ~/OrangeFox_sync
          cd ~/OrangeFox_sync
          git clone https://gitlab.com/OrangeFox/sync.git # (or, using ssh, "git clone git@gitlab.com:OrangeFox/sync.git")
          cd ~/OrangeFox_sync/sync/
          ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1

      - name: ⭐ Place device trees and kernel
        run: |
          cd ~/fox_12.1 # (or whichever directory hosts the synced manifest)
          git clone https://codeberg.org/DogDayAndroid/twrp_xiaomi_thyme device/xiaomi/thyme

      - name: 🚄 Build it
        run: |
          cd ~/OrangeFox
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_BUILD_DEVICE=thyme
          export LC_ALL="C"
          lunch twrp_thyme-eng && mka adbd bootimage

      - name: Take the OrangeFox build
        uses: actions/upload-artifact@v3
        with:
          name: OrangeFox
          path: out/target/product/thyme/*